<?php

namespace App\Appearance;

use InvalidArgumentException;

/**
 * The built-in themes (resources/themes/*.json) and the stylesheet made
 * from them. Presets and custom themes (M2) will be rendered with the same
 * Theme::toCss(), so every theme reaches the page the same way.
 */
final class Themes
{
    /** The generated stylesheet, relative to the project root. */
    public const STYLESHEET = 'resources/css/themes/themes.css';

    /** The sentinel theme the browser test injects (ADR 0003 §6.3). */
    public const SENTINEL_FIXTURE = 'tests/Browser/fixtures/sentinel-theme.json';

    private ?array $themes = null;

    public function __construct(private readonly string $directory) {}

    /** @return array<string, Theme> keyed by ID, sorted */
    public function all(): array
    {
        if ($this->themes === null) {
            $themes = [];
            foreach (glob($this->directory.'/*.json') ?: [] as $path) {
                $theme = Theme::load($path);
                if (basename($path, '.json') !== $theme->id) {
                    throw new InvalidArgumentException("{$path}: the file name must match the theme ID.");
                }
                $themes[$theme->id] = $theme;
            }
            ksort($themes);
            $this->themes = $themes;
        }

        return $this->themes;
    }

    public function get(string $id): Theme
    {
        return $this->all()[$id] ?? throw new InvalidArgumentException("Unknown theme {$id}.");
    }

    /**
     * The stylesheet: the default light theme also on :root, so the page is
     * themed before any attribute is set, then every theme under its own
     * [data-theme] selector.
     */
    public function stylesheet(string $defaultLight): string
    {
        $themes = $this->all();
        $default = $this->get($defaultLight);
        unset($themes[$defaultLight]);

        $css = "/*\n| Generated by `php artisan vistud:themes:build` from resources/themes/*.json.\n"
            ."| Do not edit: change the theme data and rebuild (DESIGN.md §3).\n*/\n\n";
        $css .= $default->toCss(":root,\n[data-theme=\"{$default->id}\"]");
        foreach ($themes as $theme) {
            $css .= "\n".$theme->toCss("[data-theme=\"{$theme->id}\"]");
        }

        return $css;
    }

    /**
     * A theme in which every colour token and every gradient stop has its
     * own improbable colour, so a browser test can prove each colour on a
     * page comes from a token. Translucent tokens stay translucent.
     *
     * @return array{css: string, colors: list<string>}
     */
    public function sentinel(): array
    {
        $template = $this->get(array_key_first($this->all()));
        $next = 0;
        $issue = function () use (&$next): Color {
            $next++;

            return new Color(0xA5, 0x17, $next);
        };

        $colors = [];
        foreach (Theme::COLORS as $token) {
            $colors[$token] = $issue()->withAlpha($template->color($token)->alpha < 1.0 ? 128 / 255 : 1.0);
        }
        $gradients = [];
        foreach (Theme::GRADIENTS as $index => $token) {
            $gradients[$token] = Gradient::linear(90 + $index, [[$issue(), 0.0], [$issue(), 50.0], [$issue(), 100.0]]);
        }
        $theme = Theme::fromData([
            'id' => 'sentinel',
            'name' => 'Sentinel',
            'scheme' => 'light',
            'colors' => array_map(fn (Color $c) => $c->toHex(), $colors),
            'gradients' => array_map(fn (Gradient $g) => $g->toData(), $gradients),
        ]);

        return [
            'css' => $theme->toCss('[data-theme="sentinel"]'),
            'colors' => array_map(fn (int $i) => "165, 23, {$i}", range(1, $next)),
        ];
    }
}
