// Copies the Lucide icons ViStud uses from lucide-static into
// resources/icons/, so the <x-icon> component can inline them without
// node_modules on the server (DESIGN.md §4.6). Add a name here, then run
// `npm run icons` and commit the result.
import { copyFileSync, readdirSync, rmSync, mkdirSync } from 'node:fs';

const icons = [
    'align-center',
    'align-justify',
    'align-left',
    'align-right',
    'app-window',
    'archive',
    'archive-restore',
    'arrow-down',
    'arrow-left',
    'arrow-left-right',
    'arrow-right',
    'arrow-up',
    'ban',
    'bell',
    'bold',
    'book-open',
    'book-open-text',
    'brain',
    'calculator',
    'calendar',
    'calendar-clock',
    'check',
    'chevron-down',
    'chevron-right',
    'chevrons-up-down',
    'circle',
    'circle-alert',
    'circle-check',
    'circle-dot',
    'circle-help',
    'clipboard-paste',
    'clock',
    'cloud-off',
    'code',
    'coffee',
    'copy',
    'download',
    'ellipsis',
    'external-link',
    'eye',
    'eye-off',
    'file',
    'file-image',
    'file-plus',
    'file-spreadsheet',
    'file-text',
    'file-up',
    'flame',
    'flask-conical',
    'folder',
    'folder-input',
    'folder-open',
    'folder-plus',
    'gallery-vertical-end',
    'globe',
    'grip-vertical',
    'heading-2',
    'heading-3',
    'highlighter',
    'history',
    'house',
    'image',
    'indent-decrease',
    'indent-increase',
    'info',
    'italic',
    'key-round',
    'keyboard',
    'landmark',
    'languages',
    'layers',
    'layout-dashboard',
    'layout-grid',
    'lightbulb',
    'link',
    'list',
    'list-ordered',
    'list-todo',
    'loader-circle',
    'log-out',
    'mail',
    'maximize-2',
    'menu',
    'message-square-text',
    'microscope',
    'minimize-2',
    'minus',
    'monitor',
    'moon',
    'music',
    'notebook-pen',
    'notebook-text',
    'palette',
    'panel-left',
    'party-popper',
    'pause',
    'pencil',
    'picture-in-picture-2',
    'play',
    'plus',
    'presentation',
    'printer',
    'redo-2',
    'remove-formatting',
    'rotate-ccw',
    'scroll-text',
    'search',
    'settings',
    'shield',
    'shield-check',
    'shield-minus',
    'shield-plus',
    'sigma',
    'sparkles',
    'square',
    'square-code',
    'strikethrough',
    'subscript',
    'sun',
    'superscript',
    'table',
    'text-quote',
    'timer',
    'trash-2',
    'trending-up',
    'triangle-alert',
    'underline',
    'undo-2',
    'unlink',
    'upload',
    'user-check',
    'user-plus',
    'users',
    'volume-2',
    'volume-x',
    'wand-sparkles',
    'x',
];

const from = 'node_modules/lucide-static/icons';
const to = 'resources/icons';

mkdirSync(to, { recursive: true });
for (const file of readdirSync(to)) {
    if (file.endsWith('.svg')) rmSync(`${to}/${file}`);
}
for (const name of icons) {
    copyFileSync(`${from}/${name}.svg`, `${to}/${name}.svg`);
}
console.log(`Copied ${icons.length} icons to ${to}.`);
